### ISSUE TITLE
Milestone 1 Submission

### ISSUE THREAD

**Issue by bharathcs** [quantum-defence/quantum-defence#13]
We've got to update and do more it seems for this part:
https://docs.google.com/presentation/d/1XTrZCGFvpKZHArQRifQVEHKubDb-vxC6X1GYuUrPPNE/present?ueb=true&slide=id.gd4e85cb41b_0_46.

Deadline: 31 May
<img width="682" alt="image" src="https://user-images.githubusercontent.com/7360964/118425753-6526fd80-b6fc-11eb-8c0b-a28fe2511864.png">

**Comment by bharathcs** [comment]
Left to do: More in depth write up in the README portion and updating all the project logs to the end of may

**Comment by Bluntsord** [comment]
Lol the prject logs srsly. Can just show them my steam hours on godot bro. For the README portion I can handle it then u review ba

**Comment by bharathcs** [comment]
alright sure
