### ISSUE TITLE
[BUG] Can't update quantum items

### ISSUE THREAD

**Issue by bharathcs** [quantum-defence/quantum-defence#74]
**Describe the bug**
The quantum items dropped into the tower do not do anything.

**To Reproduce**
1. Create a tower 
2. Click on tower
3. Drag a Not / H gate into their quantum slot

**Expected behavior**
* Tower is updated with its circuit changed, isTensor changed
* Probability bar will change based on the above ^

**Screenshots**

https://user-images.githubusercontent.com/7360964/125186931-97b62800-e25f-11eb-9df6-a2c610cfd296.mp4

**Desktop (please complete the following information):**
 - Mac, App v0.9

**Comment by Bluntsord** [comment]
https://user-images.githubusercontent.com/64136922/125235841-a9f29d80-e315-11eb-97fa-b4a52f3cb4f1.mp4

Describe the bug
Probabilities not right

To Reproduce
Steps to reproduce the behavior:
    1.Equip H gate
    2. Equip X gate
    3. Remove H gate
Expected behavior
    Change back to 100 percent when H gate is taken off.

**Comment by bharathcs** [comment]
I fixed the bug mentioned above but found anther issue unrelated to this (watch the H gate being put back)

https://user-images.githubusercontent.com/7360964/125238543-f344ec00-e319-11eb-9681-be8443d7946b.mov

**Comment by bharathcs** [comment]
I made a new issue for this, feel free to merge PR #77
